name: My Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "run build script"
        run: bash build.sh

      - name: "run unit tests"
        run: bash unit-tests.sh

  scan:
    name: Scan
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "perform software security scan"
        run: bash broken-scanner.sh
